const cfg = @import("config.zig");
const assetsRoot = cfg.assetsRoot;

pub fn Textures(comptime T: type) type {
    return struct {
        playerLeft1: T,
        playerLeft2: T,
        playerRight1: T,
        playerRight2: T,
        playerUp1: T,
        playerUp2: T,
        playerDown1: T,
        playerDown2: T,

        carBlueLeft1: T,
        carBlueLeft2: T,
        carBlueRight1: T,
        carBlueRight2: T,
        carBlueUp1: T,
        carBlueUp2: T,
        carBlueDown1: T,
        carBlueDown2: T,

        carBlackLeft1: T,
        carBlackLeft2: T,
        carBlackRight1: T,
        carBlackRight2: T,
        carBlackUp1: T,
        carBlackUp2: T,
        carBlackDown1: T,
        carBlackDown2: T,

        carRedLeft1: T,
        carRedLeft2: T,
        carRedRight1: T,
        carRedRight2: T,
        carRedUp1: T,
        carRedUp2: T,
        carRedDown1: T,
        carRedDown2: T,

        carGreenLeft1: T,
        carGreenLeft2: T,
        carGreenRight1: T,
        carGreenRight2: T,
        carGreenUp1: T,
        carGreenUp2: T,
        carGreenDown1: T,
        carGreenDown2: T,

        carWhiteLeft1: T,
        carWhiteLeft2: T,
        carWhiteRight1: T,
        carWhiteRight2: T,
        carWhiteUp1: T,
        carWhiteUp2: T,
        carWhiteDown1: T,
        carWhiteDown2: T,

        carPurpleLeft1: T,
        carPurpleLeft2: T,
        carPurpleRight1: T,
        carPurpleRight2: T,
        carPurpleUp1: T,
        carPurpleUp2: T,
        carPurpleDown1: T,
        carPurpleDown2: T,

        roadTileset: T,

        roadUp: T,
        roadDown: T,
        roadLeft: T,
        roadRight: T,
        roadIntersectionTopLeft: T,
        roadIntersectionTopRight: T,
        roadIntersectionBottomLeft: T,
        roadIntersectionBottomRight: T,
        roadCornerTopLeft: T,
        roadCornerTopRight: T,
        roadCornerBottomLeft: T,
        roadCornerBottomRight: T,

        houseBlue: T,
        houseGreen: T,
        houseOrange: T,
        houseRed: T,
        park: T,

        fenceX: T,
        fenceY: T,
        fenceTopLeft: T,
        fenceTopRight: T,
        fenceBottomLeft: T,
        fenceBottomRight: T,

        pedestrianBlueIdle: T,
        pedestrianBlueWalk1: T,
        pedestrianBlueWalk2: T,
        pedestrianBlueWalk3: T,
        pedestrianBlueWalk4: T,

        pedestrianRedIdle: T,
        pedestrianRedWalk1: T,
        pedestrianRedWalk2: T,
        pedestrianRedWalk3: T,
        pedestrianRedWalk4: T,

        airPlane: T,

        targetArrow: T,
    };
}

pub const texturePaths = Textures([*:0]const u8){
    .playerLeft1 = assetsRoot ++ "player-left-1.png",
    .playerLeft2 = assetsRoot ++ "player-left-2.png",
    .playerRight1 = assetsRoot ++ "player-right-1.png",
    .playerRight2 = assetsRoot ++ "player-right-2.png",
    .playerUp1 = assetsRoot ++ "player-up-1.png",
    .playerUp2 = assetsRoot ++ "player-up-2.png",
    .playerDown1 = assetsRoot ++ "player-down-1.png",
    .playerDown2 = assetsRoot ++ "player-down-2.png",

    .carBlueLeft1 = assetsRoot ++ "player-left-1.png",
    .carBlueLeft2 = assetsRoot ++ "player-left-2.png",
    .carBlueRight1 = assetsRoot ++ "player-right-1.png",
    .carBlueRight2 = assetsRoot ++ "player-right-2.png",
    .carBlueUp1 = assetsRoot ++ "player-up-1.png",
    .carBlueUp2 = assetsRoot ++ "player-up-2.png",
    .carBlueDown1 = assetsRoot ++ "player-down-1.png",
    .carBlueDown2 = assetsRoot ++ "player-down-2.png",

    .carBlackLeft1 = assetsRoot ++ "car-black-left-1.png",
    .carBlackLeft2 = assetsRoot ++ "car-black-left-2.png",
    .carBlackRight1 = assetsRoot ++ "car-black-right-1.png",
    .carBlackRight2 = assetsRoot ++ "car-black-right-2.png",
    .carBlackUp1 = assetsRoot ++ "car-black-up-1.png",
    .carBlackUp2 = assetsRoot ++ "car-black-up-2.png",
    .carBlackDown1 = assetsRoot ++ "car-black-down-1.png",
    .carBlackDown2 = assetsRoot ++ "car-black-down-2.png",

    .carRedLeft1 = assetsRoot ++ "car-red-left-1.png",
    .carRedLeft2 = assetsRoot ++ "car-red-left-2.png",
    .carRedRight1 = assetsRoot ++ "car-red-right-1.png",
    .carRedRight2 = assetsRoot ++ "car-red-right-2.png",
    .carRedUp1 = assetsRoot ++ "car-red-up-1.png",
    .carRedUp2 = assetsRoot ++ "car-red-up-2.png",
    .carRedDown1 = assetsRoot ++ "car-red-down-1.png",
    .carRedDown2 = assetsRoot ++ "car-red-down-2.png",

    .carGreenLeft1 = assetsRoot ++ "car-green-left-1.png",
    .carGreenLeft2 = assetsRoot ++ "car-green-left-2.png",
    .carGreenRight1 = assetsRoot ++ "car-green-right-1.png",
    .carGreenRight2 = assetsRoot ++ "car-green-right-2.png",
    .carGreenUp1 = assetsRoot ++ "car-green-up-1.png",
    .carGreenUp2 = assetsRoot ++ "car-green-up-2.png",
    .carGreenDown1 = assetsRoot ++ "car-green-down-1.png",
    .carGreenDown2 = assetsRoot ++ "car-green-down-2.png",

    .carWhiteLeft1 = assetsRoot ++ "car-white-left-1.png",
    .carWhiteLeft2 = assetsRoot ++ "car-white-left-2.png",
    .carWhiteRight1 = assetsRoot ++ "car-white-right-1.png",
    .carWhiteRight2 = assetsRoot ++ "car-white-right-2.png",
    .carWhiteUp1 = assetsRoot ++ "car-white-up-1.png",
    .carWhiteUp2 = assetsRoot ++ "car-white-up-2.png",
    .carWhiteDown1 = assetsRoot ++ "car-white-down-1.png",
    .carWhiteDown2 = assetsRoot ++ "car-white-down-2.png",

    .carPurpleLeft1 = assetsRoot ++ "car-purple-left-1.png",
    .carPurpleLeft2 = assetsRoot ++ "car-purple-left-2.png",
    .carPurpleRight1 = assetsRoot ++ "car-purple-right-1.png",
    .carPurpleRight2 = assetsRoot ++ "car-purple-right-2.png",
    .carPurpleUp1 = assetsRoot ++ "car-purple-up-1.png",
    .carPurpleUp2 = assetsRoot ++ "car-purple-up-2.png",
    .carPurpleDown1 = assetsRoot ++ "car-purple-down-1.png",
    .carPurpleDown2 = assetsRoot ++ "car-purple-down-2.png",

    .roadTileset = assetsRoot ++ "road-tileset-conditioned.png",

    .roadUp = assetsRoot ++ "road-up.png",
    .roadDown = assetsRoot ++ "road-down.png",
    .roadLeft = assetsRoot ++ "road-left.png",
    .roadRight = assetsRoot ++ "road-right.png",
    .roadIntersectionTopLeft = assetsRoot ++ "road-intersection-top-left.png",
    .roadIntersectionTopRight = assetsRoot ++ "road-intersection-top-right.png",
    .roadIntersectionBottomLeft = assetsRoot ++ "road-intersection-bottom-left.png",
    .roadIntersectionBottomRight = assetsRoot ++ "road-intersection-bottom-right.png",
    .roadCornerTopLeft = assetsRoot ++ "road-corner-top-left.png",
    .roadCornerTopRight = assetsRoot ++ "road-corner-top-right.png",
    .roadCornerBottomLeft = assetsRoot ++ "road-corner-bottom-left.png",
    .roadCornerBottomRight = assetsRoot ++ "road-corner-bottom-right.png",

    .houseBlue = assetsRoot ++ "house-blue.png",
    .houseGreen = assetsRoot ++ "house-green.png",
    .houseOrange = assetsRoot ++ "house-orange.png",
    .houseRed = assetsRoot ++ "house-red.png",
    .park = assetsRoot ++ "park.png",

    .fenceX = assetsRoot ++ "fence-left.png",
    .fenceY = assetsRoot ++ "fence-top.png",
    .fenceTopLeft = assetsRoot ++ "fence-top-left.png",
    .fenceTopRight = assetsRoot ++ "fence-top-right.png",
    .fenceBottomLeft = assetsRoot ++ "fence-bottom-left.png",
    .fenceBottomRight = assetsRoot ++ "fence-bottom-right.png",

    .pedestrianBlueIdle = assetsRoot ++ "pedestrian-blue.png",
    .pedestrianBlueWalk1 = assetsRoot ++ "pedestrian-blue-walk-1.png",
    .pedestrianBlueWalk2 = assetsRoot ++ "pedestrian-blue-walk-2.png",
    .pedestrianBlueWalk3 = assetsRoot ++ "pedestrian-blue-walk-3.png",
    .pedestrianBlueWalk4 = assetsRoot ++ "pedestrian-blue-walk-4.png",

    .pedestrianRedIdle = assetsRoot ++ "pedestrian-red.png",
    .pedestrianRedWalk1 = assetsRoot ++ "pedestrian-red-walk-1.png",
    .pedestrianRedWalk2 = assetsRoot ++ "pedestrian-red-walk-2.png",
    .pedestrianRedWalk3 = assetsRoot ++ "pedestrian-red-walk-3.png",
    .pedestrianRedWalk4 = assetsRoot ++ "pedestrian-red-walk-4.png",

    .airPlane = assetsRoot ++ "plane.png",

    .targetArrow = assetsRoot ++ "target-arrow.png",
};
